### ISSUE TITLE
Python examples fail with error

### ISSUE THREAD

**Issue by GlenHenshaw** [Kinovarobotics/Kinova-kortex2_Gen3_G3L#212]
## Description

After installing the Kortex_api-2.6.0.post3-py3-none-any.whl, I would expect the python examples to run successfully. However, I receive the error message

     Traceback (most recent call last):
        File "/Users/glenhenshaw/dev/Kinova-kortex2_Gen3_G3L/api_python/examples/100-Overview/01-devices_routing.py", line 18, in <module>
          from kortex_api.RouterClient import RouterClientSendOptions
        File "/usr/local/lib/python3.9/site-packages/kortex_api/RouterClient.py", line 3, in <module>
          from .autogen.messages import Frame_pb2 as FramePb  # NOQA
        File "/usr/local/lib/python3.9/site-packages/kortex_api/autogen/messages/Frame_pb2.py", line 11, in <module>
          from google.protobuf import descriptor_pb2
        File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor_pb2.py", line 1822, in <module>
          FileDescriptorSet = _reflection.GeneratedProtocolMessageType('FileDescriptorSet', (_message.Message,), dict(
      TypeError: Expected a message Descriptor, got Descriptor

## Version

Kortex API version 2.6.0

KortexAPI :

Kortex Device :

## Steps to reproduce

    > git clone https://github.com/Kinovarobotics/Kinova-kortex2_Gen3_G3L
    > python3 -m pip install https://artifactory.kinovaapps.com/artifactory/generic-public/kortex/API/2.6.0/kortex_api-2.6.0.post3-py3-none-any.whl
    > cd 000-Getting_started
    > python3 01-api_creation.py

## Expected behavior

I expect the code to execute without errors.

**Comment by martinleroux** [comment]
Hi @GlenHenshaw ,
Try the following:
[download the .whl file]
pip install protobuf==3.20 deprecated==1.2.7
pip install </path/to/.whl>  --no-deps
